#!/usr/bin/env python3
"""
HTML Report Generator - Beautiful shareable reports
FIXED: Renamed template vars to avoid collision with dict.items
"""
import os
import json
from datetime import datetime
from typing import Dict, Any, List

try:
    from jinja2 import Template
    JINJA_AVAILABLE = True
except ImportError:
    JINJA_AVAILABLE = False
    print("⚠️  jinja2 not installed. Run: pip install jinja2")


HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>PAKSIM Report - {{ title }}</title>
<style>
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body {
    font-family: 'Courier New', monospace;
    background: #0a0e14;
    color: #e6e6e6;
    padding: 20px;
    line-height: 1.6;
  }
  .container { max-width: 1000px; margin: 0 auto; }
  .header {
    border: 2px solid #00ff9d;
    background: linear-gradient(135deg, #0a0e14 0%, #1a1f2e 100%);
    padding: 30px;
    margin-bottom: 20px;
    position: relative;
    overflow: hidden;
  }
  .header::before {
    content: '';
    position: absolute;
    top: 0; left: 0; right: 0; bottom: 0;
    background: repeating-linear-gradient(
      0deg,
      transparent,
      transparent 2px,
      rgba(0, 255, 157, 0.03) 2px,
      rgba(0, 255, 157, 0.03) 4px
    );
    pointer-events: none;
  }
  h1 {
    color: #00ff9d;
    font-size: 2em;
    text-shadow: 0 0 10px rgba(0, 255, 157, 0.5);
    margin-bottom: 10px;
  }
  .meta { color: #888; font-size: 0.9em; }
  .meta span { color: #00ff9d; }
  .section {
    border: 1px solid #1a1f2e;
    background: #0d1219;
    padding: 20px;
    margin-bottom: 20px;
    border-left: 4px solid #00ff9d;
  }
  .section-title {
    color: #00ff9d;
    font-size: 1.2em;
    margin-bottom: 15px;
    text-transform: uppercase;
    letter-spacing: 2px;
  }
  .row {
    display: flex;
    padding: 8px 0;
    border-bottom: 1px solid #1a1f2e;
  }
  .row:last-child { border-bottom: none; }
  .label {
    width: 180px;
    color: #6c7293;
    font-weight: bold;
    flex-shrink: 0;
  }
  .value {
    color: #e6e6e6;
    word-break: break-all;
    flex-grow: 1;
  }
  .value.highlight { color: #00ff9d; }
  .value.warning { color: #ffcc00; }
  .value.danger { color: #ff3366; }
  .badge {
    display: inline-block;
    padding: 3px 10px;
    border-radius: 12px;
    font-size: 0.8em;
    font-weight: bold;
  }
  .badge.success { background: #00ff9d; color: #0a0e14; }
  .badge.fail { background: #ff3366; color: #fff; }
  pre {
    background: #060810;
    border: 1px solid #1a1f2e;
    padding: 15px;
    overflow-x: auto;
    color: #00ff9d;
    font-size: 0.85em;
  }
  .footer {
    text-align: center;
    color: #4a4a4a;
    margin-top: 40px;
    padding: 20px;
    border-top: 1px solid #1a1f2e;
    font-size: 0.85em;
  }
</style>
</head>
<body>
<div class="container">
  <div class="header">
    <h1>👻 PAKSIM-CLI Report</h1>
    <div class="meta">
      <div>Query Type: <span>{{ query_type }}</span></div>
      <div>Query Value: <span>{{ query_value }}</span></div>
      <div>Generated: <span>{{ generated_at }}</span></div>
      <div>Ghost Mode: <span>{% if ghost_mode %}ACTIVE 👻{% else %}INACTIVE{% endif %}</span></div>
      <div>Author: <span>{{ author }}</span></div>
    </div>
  </div>

  {% for section in sections %}
  <div class="section">
    <div class="section-title">{{ section.title }}</div>
    {% for row in section['rows'] %}
    <div class="row">
      <div class="label">{{ row.label }}</div>
      <div class="value {{ row.css_class }}">{{ row.value }}</div>
    </div>
    {% endfor %}
  </div>
  {% endfor %}

  {% if raw_json %}
  <div class="section">
    <div class="section-title">Raw Data</div>
    <pre>{{ raw_json }}</pre>
  </div>
  {% endif %}

  <div class="footer">
    Generated by PAKSIM-CLI v6.0 · Author: Shayan Khan<br>
    For educational &amp; security research purposes only
  </div>
</div>
</body>
</html>
"""


def generate_report(
    query_type: str,
    query_value: str,
    sections: List[Dict],
    ghost_mode: bool = False,
    author: str = "Shayan Khan",
    raw_json: Any = None,
    output_dir: str = None,
) -> str:
    """Generate an HTML report and return the file path"""
    
    if not JINJA_AVAILABLE:
        raise RuntimeError("jinja2 not installed. Run: pip install jinja2")
    
    if output_dir is None:
        output_dir = os.path.expanduser("~/.paksim/reports")
    os.makedirs(output_dir, exist_ok=True)
    
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    safe_value = "".join(c for c in query_value if c.isalnum() or c in "-_")
    filename = f"{query_type}_{safe_value}_{timestamp}.html"
    filepath = os.path.join(output_dir, filename)
    
    template = Template(HTML_TEMPLATE)
    
    html = template.render(
        title=f"{query_type} - {query_value}",
        query_type=query_type.upper(),
        query_value=query_value,
        generated_at=datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        ghost_mode=ghost_mode,
        author=author,
        sections=sections,
        raw_json=json.dumps(raw_json, indent=2, ensure_ascii=False) if raw_json else None,
    )
    
    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(html)
    
    return filepath


def sections_from_sim_result(result: Dict, query: str) -> List[Dict]:
    """Build report sections from a SIM/CNIC result"""
    sections = []
    
    if "data" in result and isinstance(result["data"], list):
        total = len(result["data"])
        
        cnic = result["data"][0].get('cni', 'N/A') if result["data"] else 'N/A'
        name = result["data"][0].get('nam', 'N/A') if result["data"] else 'N/A'
        
        # Summary section — note key is 'rows', not 'items'
        sections.append({
            "title": "📊 Summary",
            "rows": [
                {"label": "Total SIMs Found", "value": str(total), "css_class": "highlight"},
                {"label": "CNIC", "value": cnic, "css_class": "highlight"},
                {"label": "Name", "value": name, "css_class": "highlight"},
            ]
        })
        
        for idx, item in enumerate(result["data"], 1):
            sections.append({
                "title": f"📱 SIM #{idx}",
                "rows": [
                    {"label": "Phone Number", "value": item.get('nbr', 'N/A'), "css_class": ""},
                    {"label": "Name", "value": item.get('nam', 'N/A'), "css_class": "highlight"},
                    {"label": "CNIC", "value": item.get('cni', 'N/A'), "css_class": "highlight"},
                    {"label": "Address", "value": item.get('adr', 'N/A'), "css_class": ""},
                ]
            })
    
    return sections


def sections_from_cnic_decode(decoded: Dict) -> List[Dict]:
    """Build report sections from a CNIC structural decode"""
    return [{
        "title": "🧬 CNIC Structural Decode",
        "rows": [
            {"label": "CNIC", "value": decoded.get('formatted', 'N/A'), "css_class": "highlight"},
            {"label": "Gender", "value": decoded.get('gender', 'N/A'), "css_class": ""},
            {"label": "Province", "value": decoded.get('province', 'N/A'), "css_class": "highlight"},
            {"label": "Division", "value": decoded.get('division', 'N/A'), "css_class": "highlight"},
            {"label": "District", "value": decoded.get('district', 'N/A'), "css_class": "highlight"},
            {"label": "Tehsil", "value": decoded.get('tehsil', 'N/A'), "css_class": "highlight"},
            {"label": "Union Council", "value": decoded.get('union_council', 'N/A'), "css_class": ""},
            {"label": "Full Path", "value": decoded.get('full_path', 'N/A'), "css_class": ""},
        ]
    }]


def sections_from_breach_result(data: Dict) -> List[Dict]:
    """Build report sections from a breach check result"""
    sections = []
    
    summary_rows = [
        {"label": "Email", "value": data.get('email', 'N/A'), "css_class": "highlight"},
        {"label": "Status", "value": "COMPROMISED" if data.get('pwned') else "CLEAN",
         "css_class": "danger" if data.get('pwned') else "highlight"},
        {"label": "Breach Count", "value": str(data.get('count', 0)), "css_class": ""},
    ]
    sections.append({"title": "📧 Summary", "rows": summary_rows})
    
    for idx, breach in enumerate(data.get("breaches", []), 1):
        sections.append({
            "title": f"💀 Breach #{idx}: {breach.get('title', 'N/A')}",
            "rows": [
                {"label": "Domain", "value": breach.get('domain', 'N/A'), "css_class": ""},
                {"label": "Date", "value": breach.get('date', 'N/A'), "css_class": ""},
                {"label": "Accounts", "value": f"{breach.get('pwn_count', 0):,}", "css_class": ""},
                {"label": "Data Leaked", "value": ", ".join(breach.get('data_classes', [])), "css_class": "warning"},
            ]
        })
    
    return sections


if __name__ == "__main__":
    # Test with sample data
    sample = {
        "data": [{
            "nbr": "03000000000",
            "nam": "TURING COMPLETE",
            "cni": "0000000000000",
            "adr": "Sector 7G, Cyberspace"
        }]
    }
    
    sections = sections_from_sim_result(sample, "03000000000")
    path = generate_report("sim", "03000000000", sections, ghost_mode=True, raw_json=sample)
    print(f"✅ Report generated: {path}")
    
    # Test CNIC decode report
    decoded_sample = {
        "formatted": "00000-0000000-0",
        "gender": "Male",
        "province": "CYBERSPACE",
        "division": "THE MATRIX",
        "district": "THE MATRIX",
        "tehsil": "TAKHT BHAI",
        "union_council": "N/A",
        "full_path": "KHYBER PAKHTUNKHWA > MARDAN > MARDAN > TAKHT BHAI",
    }
    sections2 = sections_from_cnic_decode(decoded_sample)
    path2 = generate_report("cnic", "00000-0000000-0", sections2, raw_json=decoded_sample)
    print(f"✅ CNIC report generated: {path2}")
